<!DOCTYPE html>
<html>
<body>
<div class="carousel-wrap">
    <div class="owl-carousel">
        <div class="item"><img src="https://m.media-amazon.com/images/I/51btXKejFiL._SX3000_.jpg"></div>
        <div class="item"><img src="https://m.media-amazon.com/images/I/51btXKejFiL._SX3000_.jpg"></div>
        <div class="item"><img src="https://m.media-amazon.com/images/I/71UMpK9x9TL._SX3000_.jpg"></div>
        <div class="item"><img src="https://m.media-amazon.com/images/I/619QIdx19yL._SX3000_.jpg"></div>
        <div class="item"><img src="https://m.media-amazon.com/images/I/61HzMg3Y+VL._SX3000_.jpg"></div>
        <div class="item"><img src="https://m.media-amazon.com/images/I/71i723QTb+L._SX3000_.jpg"></div>
        <div class="item"><img src="https://m.media-amazon.com/images/I/71wCZE4P7xL._SX3000_.jpg"></div>
    </div>
</div>
</body>
</html>